### ISSUE TITLE
taskcafe_web_1 exited with code 1

### ISSUE THREAD

**Issue by ParmuSingh** [JordanKnott/taskcafe#87] opened 2020-12-03 16:37 UTC
I used docker-compose to install. When running `docker-compose -p taskcafe up -d` both database and web server start but when I check the web server isn't running. Running this command without `-d` I get these logs:

```
root@raspberrypi:/home/pi/selfhosted/taskcafe/taskcafe# docker-compose -p taskcafe up
taskcafe_postgres_1 is up-to-date
Starting taskcafe_web_1 ... done
Attaching to taskcafe_postgres_1, taskcafe_web_1
web_1       | standard_init_linux.go:207: exec user process caused "exec format error"
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting default time zone ... UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | sh: locale: not found
postgres_1  | 2020-12-03 16:09:27.746 UTC [29] WARNING:  no usable system locales were found
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ... ok
postgres_1  | 
postgres_1  | initdb: warning: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | 
postgres_1  | Success. You can now start the database server using:
postgres_1  | 
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  | 
postgres_1  | waiting for server to start....2020-12-03 16:09:32.211 UTC [34] LOG:  starting PostgreSQL 12.3 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 9.3.0) 9.3.0, 32-bit
postgres_1  | 2020-12-03 16:09:32.219 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-03 16:09:32.282 UTC [35] LOG:  database system was shut down at 2020-12-03 16:09:30 UTC
postgres_1  | 2020-12-03 16:09:32.293 UTC [34] LOG:  database system is ready to accept connections
postgres_1  |  done
postgres_1  | server started
postgres_1  | CREATE DATABASE
postgres_1  | 
postgres_1  | 
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  | 
postgres_1  | 2020-12-03 16:09:33.005 UTC [34] LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down....2020-12-03 16:09:33.010 UTC [34] LOG:  aborting any active transactions
postgres_1  | 2020-12-03 16:09:33.015 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
postgres_1  | 2020-12-03 16:09:33.015 UTC [36] LOG:  shutting down
postgres_1  | 2020-12-03 16:09:33.061 UTC [34] LOG:  database system is shut down
postgres_1  |  done
postgres_1  | server stopped
postgres_1  | 
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2020-12-03 16:09:33.144 UTC [1] LOG:  starting PostgreSQL 12.3 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 9.3.0) 9.3.0, 32-bit
postgres_1  | 2020-12-03 16:09:33.144 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-12-03 16:09:33.144 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-12-03 16:09:33.152 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-03 16:09:33.235 UTC [45] LOG:  database system was shut down at 2020-12-03 16:09:33 UTC
postgres_1  | 2020-12-03 16:09:33.250 UTC [1] LOG:  database system is ready to accept connections
postgres_1  | 2020-12-03 16:29:16.829 UTC [1] LOG:  received smart shutdown request
postgres_1  | 2020-12-03 16:29:16.838 UTC [1] LOG:  background worker "logical replication launcher" (PID 51) exited with exit code 1
postgres_1  | 2020-12-03 16:29:16.844 UTC [46] LOG:  shutting down
postgres_1  | 2020-12-03 16:29:16.888 UTC [1] LOG:  database system is shut down
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2020-12-03 16:29:23.643 UTC [1] LOG:  starting PostgreSQL 12.3 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 9.3.0) 9.3.0, 32-bit
postgres_1  | 2020-12-03 16:29:23.643 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-12-03 16:29:23.644 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-12-03 16:29:23.653 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-03 16:29:23.728 UTC [21] LOG:  database system was shut down at 2020-12-03 16:29:16 UTC
postgres_1  | 2020-12-03 16:29:23.740 UTC [1] LOG:  database system is ready to accept connections
taskcafe_web_1 exited with code 1
```

It seems the web server is crashing. I am running this on my raspberry pi 4.

**Comment by ParmuSingh** [comment] 2020-12-03 19:44
Docker compose version: 1.21.0. Build unknown.

Installed via apt-get on raspian.

**Comment by Fernthedev** [comment] 2020-12-03 19:48
`standard_init_linux.go:207: exec user process caused "exec format error"` 
May or may not be the cause. Does Docker on arm work nicely with x86_64/amd64 compiled golang binaries?

**Comment by ParmuSingh** [comment] 2020-12-03 19:53
I sure don't have much experience to comment on arm compatibility. I will try to install from source and update.

**Comment by JordanKnott** [comment] 2020-12-03 21:47
Well that's odd - however judging by the logs it doesn't appear to be an issue with taskcafe itself but possibly something to do with your setup or docker install. Closing as this is not something I can provide any help on.

**Closed by JordanKnott** 2020-12-03 21:47 UTC

**Comment by ParmuSingh** [comment] 2020-12-03 23:22
Update: I compiled from source and its working.

**Comment by dongshimou** [comment] 2021-01-17 15:04
same question.

**Comment by ParmuSingh** [comment] 2021-01-18 10:57
> same question.

Are you running on ARM processor?

**Comment by dongshimou** [comment] 2021-02-10 13:33
@ParmuSingh yes, raspberry pi 4.

**Comment by ParmuSingh** [comment] 2021-02-10 13:36
@dongshimou follow the build from source instructions. The only thing not mentioned in wiki is configuring database. Simply create a database for taskcafe in postgres as mentioned in the config file. Other than that everything is mentioned in wiki.

**Comment by Cyber1000** [comment] 2022-03-27 11:27
@JordanKnott I think the "problem" is that your docker-image is linux/amd64 only and not arm64. how to you create your docker-image? Manually? I couldn't find a .github/workflow-file ... I think the best would be to build with docker buildx, there is a github action for this: https://github.com/docker/setup-buildx-action
I've done something similar (but didn't need to push it to dockerhub)
