### ISSUE TITLE
Bug: Unable to install on Raspberry PI 3b+

### ISSUE THREAD

**Issue by peakstack** [JordanKnott/taskcafe#38] opened 2020-08-22 12:53 UTC
I am unable to install the application on the raspberry pi 3b+ via docker-compose.
It always stops on the same step.

Step 5/18 : RUN yarn install
 ---> Running in cecec8496575
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.12.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1

**Comment by JordanKnott** [comment] 2020-10-01 00:38
For some reason the install and more specifically build step require a large amount of RAM in order to
build the production frontend. I'm not entirely sure how to fix this (as I've tried to get this to build on my build server and it refused). If I figure out a way I'll update this ticket, but for now I'm going to close it and add a note to the README.

**Closed by JordanKnott** 2020-10-01 00:38 UTC

**Comment by maksimov** [comment] 2020-10-01 01:04
@peakstack can you download https://registry.yarnpkg.com/@fortawesome/free-solid-svg-icons/-/free-solid-svg-icons-5.12.1.tgz manually from your Raspberry Pi? If you get a timeout then the issue is indeed with your network (e.g. DNS is flaky?)
Afaik what yarn is doing there is a simple enough file download, nothing special.
